### ISSUE TITLE
yml文件中有个ai的pyth没有配置嘛

### ISSUE THREAD

**Issue by crucistau** [raxcl/raxcl-blog#3]
项目拉到本地，改完数据库后出现这个问题
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aiMysqlBackupScheduleTask': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'ai-backup.qi-niu-yun.path' in value "${ai-backup.qi-niu-yun.path}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at cn.raxcl.BlogApiApplication.main(BlogApiApplication.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'ai-backup.qi-niu-yun.path' in value "${ai-backup.qi-niu-yun.path}"

**Comment by munaniu** [comment]
![test](https://github.com/user-attachments/assets/96f9f87d-2b7b-4a50-87fd-1c034d3f13a3)
如上改动了下能跑起来，供参考，改动如有缺陷还望提醒

**Comment by Raxcl** [comment]
感谢你的提醒，这是因为借用了这个项目的定时任务跑了其他服务，或许我应该考虑将 master 分支作为开源分支，以保证大家的项目能顺利运行，这两天优化一下

**Comment by munaniu** [comment]
@Raxcl 请问后台密码是什么呢？
前台的很帅，辛苦了，谢谢

**Comment by Raxcl** [comment]
我猜你一定没有看 readme（如果看了就一定会发现密码：666666）

**Comment by munaniu** [comment]
看过了，正时因为登不上所以问一下，尝试过了666666，test，admin
![image](https://github.com/user-attachments/assets/6d41eba2-2801-4ee5-8e53-2dcc8a5f55e5)

**Comment by Raxcl** [comment]
那我猜你肯定忽略了账号名并不是 admin

**Comment by munaniu** [comment]
@Raxcl 是的是的，登上了，谢谢
